<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder {
    /**
    * Run the database seeds.
    */

    public function run(): void {
        $products = [
            [
                'id'=> 1,
                'title'=> 'iPhone 9',
                'description'=> 'An apple mobile which is nothing like apple',
                'price'=> '549.00',
                'discountPercentage'=> '12.96',
                'rating'=> '4.69',
                'stock'=> 94,
                'brand'=> 'Apple',
                'category'=> 'smartphones',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/1/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/1/1.jpg', 'https://cdn.dummyjson.com/product-images/1/2.jpg', 'https://cdn.dummyjson.com/product-images/1/3.jpg', 'https://cdn.dummyjson.com/product-images/1/4.jpg', 'https://cdn.dummyjson.com/product-images/1/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 2,
                'title'=> 'iPhone X',
                'description'=> 'SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...',
                'price'=> '899.00',
                'discountPercentage'=> '17.94',
                'rating'=> '4.44',
                'stock'=> 34,
                'brand'=> 'Apple',
                'category'=> 'smartphones',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/2/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/2/1.jpg', 'https://cdn.dummyjson.com/product-images/2/2.jpg', 'https://cdn.dummyjson.com/product-images/2/3.jpg', 'https://cdn.dummyjson.com/product-images/2/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 3,
                'title'=> 'Samsung Universe 9',
                'description'=> "Samsung's new variant which goes beyond Galaxy to the Universe",
                'price'=> '1249.00',
                'discountPercentage'=> '15.46',
                'rating'=> '4.09',
                'stock'=> 36,
                'brand'=> 'Samsung',
                'category'=> 'smartphones',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/3/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/3/1.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 4,
                'title'=> 'OPPOF19',
                'description'=> 'OPPO F19 is officially announced on April 2021.',
                'price'=> '280.00',
                'discountPercentage'=> '17.91',
                'rating'=> '4.30',
                'stock'=> 123,
                'brand'=> 'OPPO',
                'category'=> 'smartphones',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/4/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/4/1.jpg', 'https://cdn.dummyjson.com/product-images/4/2.jpg', 'https://cdn.dummyjson.com/product-images/4/3.jpg', 'https://cdn.dummyjson.com/product-images/4/4.jpg', 'https://cdn.dummyjson.com/product-images/4/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 5,
                'title'=> 'Huawei P30',
                'description'=> 'Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.',
                'price'=> '499.00',
                'discountPercentage'=> '10.58',
                'rating'=> '4.09',
                'stock'=> 32,
                'brand'=> 'Huawei',
                'category'=> 'smartphones',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/5/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/5/1.jpg', 'https://cdn.dummyjson.com/product-images/5/2.jpg', 'https://cdn.dummyjson.com/product-images/5/3.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 6,
                'title'=> 'MacBook Pro',
                'description'=> 'MacBook Pro 2021 with mini-LED display may launch between September, November',
                'price'=> '1749.00',
                'discountPercentage'=> '11.02',
                'rating'=> '4.57',
                'stock'=> 83,
                'brand'=> 'Apple',
                'category'=> 'laptops',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/6/thumbnail.png',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/6/1.png', 'https://cdn.dummyjson.com/product-images/6/2.jpg', 'https://cdn.dummyjson.com/product-images/6/3.png', 'https://cdn.dummyjson.com/product-images/6/4.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 7,
                'title'=> 'Samsung Galaxy Book',
                'description'=> 'Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched',
                'price'=> '1499.00',
                'discountPercentage'=> '4.15',
                'rating'=> '4.25',
                'stock'=> 50,
                'brand'=> 'Samsung',
                'category'=> 'laptops',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/7/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/7/1.jpg', 'https://cdn.dummyjson.com/product-images/7/2.jpg', 'https://cdn.dummyjson.com/product-images/7/3.jpg', 'https://cdn.dummyjson.com/product-images/7/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 8,
                'title'=> 'Microsoft Surface Laptop 4',
                'description'=> 'Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.',
                'price'=> '1499.00',
                'discountPercentage'=> '10.23',
                'rating'=> '4.43',
                'stock'=> 68,
                'brand'=> 'Microsoft Surface',
                'category'=> 'laptops',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/8/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/8/1.jpg', 'https://cdn.dummyjson.com/product-images/8/2.jpg', 'https://cdn.dummyjson.com/product-images/8/3.jpg', 'https://cdn.dummyjson.com/product-images/8/4.jpg', 'https://cdn.dummyjson.com/product-images/8/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 9,
                'title'=> 'Infinix INBOOK',
                'description'=> 'Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty',
                'price'=> '1099.00',
                'discountPercentage'=> '11.83',
                'rating'=> '4.54',
                'stock'=> 96,
                'brand'=> 'Infinix',
                'category'=> 'laptops',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/9/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/9/1.jpg', 'https://cdn.dummyjson.com/product-images/9/2.png', 'https://cdn.dummyjson.com/product-images/9/3.png', 'https://cdn.dummyjson.com/product-images/9/4.jpg', 'https://cdn.dummyjson.com/product-images/9/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 10,
                'title'=> 'HP Pavilion 15-DK1056WM',
                'description'=> 'HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10',
                'price'=> '1099.00',
                'discountPercentage'=> '6.18',
                'rating'=> '4.43',
                'stock'=> 89,
                'brand'=> 'HP Pavilion',
                'category'=> 'laptops',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/10/1.jpg', 'https://cdn.dummyjson.com/product-images/10/2.jpg', 'https://cdn.dummyjson.com/product-images/10/3.jpg', 'https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 11,
                'title'=> 'perfume Oil',
                'description'=> 'Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil',
                'price'=> '13.00',
                'discountPercentage'=> '8.40',
                'rating'=> '4.26',
                'stock'=> 65,
                'brand'=> 'Mega',
                'category'=> 'perfume',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/11/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/11/1.jpg', 'https://cdn.dummyjson.com/product-images/11/2.jpg', 'https://cdn.dummyjson.com/product-images/11/3.jpg', 'https://cdn.dummyjson.com/product-images/11/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 12,
                'title'=> 'Cologne Oil',
                'description'=> 'Impression of AquaDiGio by GiorgioArmani concentrated attar perfume oil',
                'price'=> '7.00',
                'discountPercentage'=> '6.60',
                'rating'=> '4.16',
                'stock'=> 84,
                'brand'=> 'AquaDiGio',
                'category'=> 'perfume',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/12/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/12/1.jpg', 'https://cdn.dummyjson.com/product-images/12/2.jpg', 'https://cdn.dummyjson.com/product-images/12/3.jpg', 'https://cdn.dummyjson.com/product-images/12/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 13,
                'title'=> 'Hair Oil',
                'description'=> 'Mega Discount, Farsali Rose Gold Elixir – 24k Gold Infused Beauty Oil',
                'price'=> '7.00',
                'discountPercentage'=> '9.30',
                'rating'=> '4.24',
                'stock'=> 22,
                'brand'=> 'Mega',
                'category'=> 'haircare',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/13/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/13/1.jpg', 'https://cdn.dummyjson.com/product-images/13/2.jpg', 'https://cdn.dummyjson.com/product-images/13/3.jpg', 'https://cdn.dummyjson.com/product-images/13/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 14,
                'title'=> 'Hair Mist',
                'description'=> 'Mega Discount, A completely innovative mist spray for hair',
                'price'=> '17.00',
                'discountPercentage'=> '9.82',
                'rating'=> '4.37',
                'stock'=> 35,
                'brand'=> 'Mega',
                'category'=> 'haircare',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/14/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/14/1.jpg', 'https://cdn.dummyjson.com/product-images/14/2.jpg', 'https://cdn.dummyjson.com/product-images/14/3.jpg', 'https://cdn.dummyjson.com/product-images/14/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 15,
                'title'=> 'Necklace Set',
                'description'=> 'Copper Silver Metal Embellished Designer Necklace Set By The Ornate Studio',
                'price'=> '36.00',
                'discountPercentage'=> '9.04',
                'rating'=> '4.11',
                'stock'=> 91,
                'brand'=> 'Ornate Studio',
                'category'=> 'jewellery',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/15/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/15/1.jpg', 'https://cdn.dummyjson.com/product-images/15/2.jpg', 'https://cdn.dummyjson.com/product-images/15/3.jpg', 'https://cdn.dummyjson.com/product-images/15/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 16,
                'title'=> 'Earrings',
                'description'=> 'Statement Studs, featuring Swarovski Crystals!',
                'price'=> '13.00',
                'discountPercentage'=> '7.25',
                'rating'=> '4.30',
                'stock'=> 54,
                'brand'=> 'Swarovski',
                'category'=> 'jewellery',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/16/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/16/1.jpg', 'https://cdn.dummyjson.com/product-images/16/2.jpg', 'https://cdn.dummyjson.com/product-images/16/3.jpg', 'https://cdn.dummyjson.com/product-images/16/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 17,
                'title'=> 'Bracelet',
                'description'=> 'Designed to fit you! Our bracelets are adjustable to every wrist size.',
                'price'=> '29.00',
                'discountPercentage'=> '6.86',
                'rating'=> '4.18',
                'stock'=> 76,
                'brand'=> 'FitsAll',
                'category'=> 'jewellery',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/17/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/17/1.jpg', 'https://cdn.dummyjson.com/product-images/17/2.jpg', 'https://cdn.dummyjson.com/product-images/17/3.jpg', 'https://cdn.dummyjson.com/product-images/17/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 18,
                'title'=> 'Handbag',
                'description'=> 'Versatile and Trendy - Handbags for every occasion',
                'price'=> '25.00',
                'discountPercentage'=> '7.11',
                'rating'=> '4.15',
                'stock'=> 67,
                'brand'=> 'Trendz',
                'category'=> 'accessories',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/18/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/18/1.jpg', 'https://cdn.dummyjson.com/product-images/18/2.jpg', 'https://cdn.dummyjson.com/product-images/18/3.jpg', 'https://cdn.dummyjson.com/product-images/18/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 19,
                'title'=> 'Sunglasses',
                'description'=> 'Fashionable Eyewear - Protect your eyes in style',
                'price'=> '19.00',
                'discountPercentage'=> '5.56',
                'rating'=> '4.12',
                'stock'=> 82,
                'brand'=> 'Trendz',
                'category'=> 'accessories',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/19/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/19/1.jpg', 'https://cdn.dummyjson.com/product-images/19/2.jpg', 'https://cdn.dummyjson.com/product-images/19/3.jpg', 'https://cdn.dummyjson.com/product-images/19/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 20,
                'title'=> 'Headphones',
                'description'=> 'Immerse yourself in the world of music with our premium headphones',
                'price'=> '49.00',
                'discountPercentage'=> '6.49',
                'rating'=> '4.28',
                'stock'=> 76,
                'brand'=> 'AudioFusion',
                'category'=> 'accessories',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/20/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/20/1.jpg', 'https://cdn.dummyjson.com/product-images/20/2.jpg', 'https://cdn.dummyjson.com/product-images/20/3.jpg', 'https://cdn.dummyjson.com/product-images/20/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:15:54.000000Z',
                'updated_at'=> '2024-05-20T23:15:54.000000Z'
            ],
            [
                'id'=> 21,
                'title'=> '- Daal Masoor 500 grams',
                'description'=> 'Fine quality Branded Product Keep in a cool and dry place',
                'price'=> '20.00',
                'discountPercentage'=> '4.81',
                'rating'=> '4.44',
                'stock'=> 133,
                'brand'=> 'Saaf & Khaas',
                'category'=> 'groceries',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/21/thumbnail.png',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/21/1.png', 'https://cdn.dummyjson.com/product-images/21/2.jpg', 'https://cdn.dummyjson.com/product-images/21/3.jpg']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 22,
                'title'=> 'Elbow Macaroni - 400 gm',
                'description'=> 'Product details of Bake Parlor Big Elbow Macaroni - 400 gm',
                'price'=> '14.00',
                'discountPercentage'=> '15.58',
                'rating'=> '4.57',
                'stock'=> 146,
                'brand'=> 'Bake Parlor Big',
                'category'=> 'groceries',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/22/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/22/1.jpg', 'https://cdn.dummyjson.com/product-images/22/2.jpg', 'https://cdn.dummyjson.com/product-images/22/3.jpg']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 23,
                'title'=> 'Orange Essence Food Flavou',
                'description'=> 'Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item',
                'price'=> '14.00',
                'discountPercentage'=> '8.04',
                'rating'=> '4.85',
                'stock'=> 26,
                'brand'=> 'Baking Food Items',
                'category'=> 'groceries',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/23/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/23/1.jpg', 'https://cdn.dummyjson.com/product-images/23/2.jpg', 'https://cdn.dummyjson.com/product-images/23/3.jpg', 'https://cdn.dummyjson.com/product-images/23/4.jpg', 'https://cdn.dummyjson.com/product-images/23/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 24,
                'title'=> 'cereals muesli fruit nuts',
                'description'=> 'original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji',
                'price'=> '46.00',
                'discountPercentage'=> '16.80',
                'rating'=> '4.94',
                'stock'=> 113,
                'brand'=> 'fauji',
                'category'=> 'groceries',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/24/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/24/1.jpg', 'https://cdn.dummyjson.com/product-images/24/2.jpg', 'https://cdn.dummyjson.com/product-images/24/3.jpg', 'https://cdn.dummyjson.com/product-images/24/4.jpg', 'https://cdn.dummyjson.com/product-images/24/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 25,
                'title'=> 'Gulab Powder 50 Gram',
                'description'=> 'Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds',
                'price'=> '70.00',
                'discountPercentage'=> '13.58',
                'rating'=> '4.87',
                'stock'=> 47,
                'brand'=> 'Dry Rose',
                'category'=> 'groceries',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/25/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/25/1.png', 'https://cdn.dummyjson.com/product-images/25/2.jpg', 'https://cdn.dummyjson.com/product-images/25/3.png', 'https://cdn.dummyjson.com/product-images/25/4.jpg', 'https://cdn.dummyjson.com/product-images/25/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 26,
                'title'=> 'Plant Hanger For Home',
                'description'=> 'Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf',
                'price'=> '41.00',
                'discountPercentage'=> '17.86',
                'rating'=> '4.08',
                'stock'=> 131,
                'brand'=> 'Boho Decor',
                'category'=> 'home-decoration',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/26/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/26/1.jpg', 'https://cdn.dummyjson.com/product-images/26/2.jpg', 'https://cdn.dummyjson.com/product-images/26/3.jpg', 'https://cdn.dummyjson.com/product-images/26/4.jpg', 'https://cdn.dummyjson.com/product-images/26/5.jpg', 'https://cdn.dummyjson.com/product-images/26/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 27,
                'title'=> 'Flying Wooden Bird',
                'description'=> 'Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm',
                'price'=> '51.00',
                'discountPercentage'=> '15.58',
                'rating'=> '4.41',
                'stock'=> 17,
                'brand'=> 'Flying Wooden',
                'category'=> 'home-decoration',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/27/thumbnail.webp',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/27/1.jpg', 'https://cdn.dummyjson.com/product-images/27/2.jpg', 'https://cdn.dummyjson.com/product-images/27/3.jpg', 'https://cdn.dummyjson.com/product-images/27/4.jpg', 'https://cdn.dummyjson.com/product-images/27/thumbnail.webp']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 28,
                'title'=> '3D Embellishment Art Lamp',
                'description'=> '3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)',
                'price'=> '20.00',
                'discountPercentage'=> '16.49',
                'rating'=> '4.82',
                'stock'=> 54,
                'brand'=> 'LED Lights',
                'category'=> 'home-decoration',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/28/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/28/1.jpg', 'https://cdn.dummyjson.com/product-images/28/2.jpg', 'https://cdn.dummyjson.com/product-images/28/3.png', 'https://cdn.dummyjson.com/product-images/28/4.jpg', 'https://cdn.dummyjson.com/product-images/28/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 29,
                'title'=> 'Handcraft Chinese style',
                'description'=> 'Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate',
                'price'=> '60.00',
                'discountPercentage'=> '15.34',
                'rating'=> '4.44',
                'stock'=> 7,
                'brand'=> 'luxury palace',
                'category'=> 'home-decoration',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/29/thumbnail.webp',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/29/1.jpg', 'https://cdn.dummyjson.com/product-images/29/2.jpg', 'https://cdn.dummyjson.com/product-images/29/3.webp', 'https://cdn.dummyjson.com/product-images/29/4.webp', 'https://cdn.dummyjson.com/product-images/29/thumbnail.webp']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 30,
                'title'=> 'Key Holder',
                'description'=> 'Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality',
                'price'=> '30.00',
                'discountPercentage'=> '2.92',
                'rating'=> '4.92',
                'stock'=> 54,
                'brand'=> 'Golden',
                'category'=> 'home-decoration',
                'thumbnail'=> 'https://cdn.dummyjson.com/product-images/30/thumbnail.jpg',
                'images'=> json_encode(['https://cdn.dummyjson.com/product-images/30/1.jpg', 'https://cdn.dummyjson.com/product-images/30/2.jpg', 'https://cdn.dummyjson.com/product-images/30/3.jpg', 'https://cdn.dummyjson.com/product-images/30/thumbnail.jpg']),
                'created_at'=> '2024-05-20T23:16:58.000000Z',
                'updated_at'=> '2024-05-20T23:16:58.000000Z'
            ],
            [
                'id'=> 31,
                'title'=> 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
                'description'=> 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday',
                'price'=> '109.95',
                'discountPercentage'=> '0.00',
                'rating'=> '3.90',
                'stock'=> 120,
                'brand'=> '',
                'category'=> "men's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 32,
                'title'=> 'Mens Casual Premium Slim Fit T-Shirts',
                'description'=> 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.',
                'price'=> '22.30',
                'discountPercentage'=> '0.00',
                'rating'=> '4.10',
                'stock'=> 259,
                'brand'=> '',
                'category'=> "men's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 33,
                'title'=> 'Mens Cotton Jacket',
                'description'=> 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.',
                'price'=> '55.99',
                'discountPercentage'=> '0.00',
                'rating'=> '4.70',
                'stock'=> 500,
                'brand'=> '',
                'category'=> "men's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 34,
                'title'=> 'Mens Casual Slim Fit',
                'description'=> 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.',
                'price'=> '15.99',
                'discountPercentage'=> '0.00',
                'rating'=> '2.10',
                'stock'=> 430,
                'brand'=> '',
                'category'=> "men's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 35,
                'title'=> "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
                'description'=> "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
                'price'=> '695.00',
                'discountPercentage'=> '0.00',
                'rating'=> '4.60',
                'stock'=> 400,
                'brand'=> '',
                'category'=> 'jewelery',
                'thumbnail'=> 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 36,
                'title'=> 'Solid Gold Petite Micropave',
                'description'=> 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.',
                'price'=> '168.00',
                'discountPercentage'=> '0.00',
                'rating'=> '3.90',
                'stock'=> 70,
                'brand'=> '',
                'category'=> 'jewelery',
                'thumbnail'=> 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 37,
                'title'=> 'White Gold Plated Princess',
                'description'=> "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
                'price'=> '9.99',
                'discountPercentage'=> '0.00',
                'rating'=> '3.00',
                'stock'=> 400,
                'brand'=> '',
                'category'=> 'jewelery',
                'thumbnail'=> 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 38,
                'title'=> 'Pierced Owl Rose Gold Plated Stainless Steel Double',
                'description'=> 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel',
                'price'=> '10.99',
                'discountPercentage'=> '0.00',
                'rating'=> '1.90',
                'stock'=> 100,
                'brand'=> '',
                'category'=> 'jewelery',
                'thumbnail'=> 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 39,
                'title'=> 'WD 2TB Elements Portable External Hard Drive - USB 3.0',
                'description'=> 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system',
                'price'=> '64.00',
                'discountPercentage'=> '0.00',
                'rating'=> '3.30',
                'stock'=> 203,
                'brand'=> '',
                'category'=> 'electronics',
                'thumbnail'=> 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 40,
                'title'=> 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
                'description'=> 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)',
                'price'=> '109.00',
                'discountPercentage'=> '0.00',
                'rating'=> '2.90',
                'stock'=> 470,
                'brand'=> '',
                'category'=> 'electronics',
                'thumbnail'=> 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 41,
                'title'=> 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
                'description'=> '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.',
                'price'=> '109.00',
                'discountPercentage'=> '0.00',
                'rating'=> '4.80',
                'stock'=> 319,
                'brand'=> '',
                'category'=> 'electronics',
                'thumbnail'=> 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 42,
                'title'=> 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',
                'description'=> "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
                'price'=> '114.00',
                'discountPercentage'=> '0.00',
                'rating'=> '4.80',
                'stock'=> 400,
                'brand'=> '',
                'category'=> 'electronics',
                'thumbnail'=> 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 43,
                'title'=> 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',
                'description'=> '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz',
                'price'=> '599.00',
                'discountPercentage'=> '0.00',
                'rating'=> '2.90',
                'stock'=> 250,
                'brand'=> '',
                'category'=> 'electronics',
                'thumbnail'=> 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 44,
                'title'=> 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED',
                'description'=> '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag',
                'price'=> '999.99',
                'discountPercentage'=> '0.00',
                'rating'=> '2.20',
                'stock'=> 140,
                'brand'=> '',
                'category'=> 'electronics',
                'thumbnail'=> 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 45,
                'title'=> "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
                'description'=> 'Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates',
                'price'=> '56.99',
                'discountPercentage'=> '0.00',
                'rating'=> '2.60',
                'stock'=> 235,
                'brand'=> '',
                'category'=> "women's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 46,
                'title'=> "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
                'description'=> '100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON',
                'price'=> '29.95',
                'discountPercentage'=> '0.00',
                'rating'=> '2.90',
                'stock'=> 340,
                'brand'=> '',
                'category'=> "women's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 47,
                'title'=> 'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
                'description'=> "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
                'price'=> '39.99',
                'discountPercentage'=> '0.00',
                'rating'=> '3.80',
                'stock'=> 679,
                'brand'=> '',
                'category'=> "women's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 48,
                'title'=> "MBJ Women's Solid Short Sleeve Boat Neck V",
                'description'=> '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem',
                'price'=> '9.85',
                'discountPercentage'=> '0.00',
                'rating'=> '4.70',
                'stock'=> 130,
                'brand'=> '',
                'category'=> "women's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 49,
                'title'=> "Opna Women's Short Sleeve Moisture",
                'description'=> '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort',
                'price'=> '7.95',
                'discountPercentage'=> '0.00',
                'rating'=> '4.50',
                'stock'=> 146,
                'brand'=> '',
                'category'=> "women's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ],
            [
                'id'=> 50,
                'title'=> 'DANVOUY Womens T Shirt Casual Cotton Short',
                'description'=> '95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.',
                'price'=> '12.99',
                'discountPercentage'=> '0.00',
                'rating'=> '3.60',
                'stock'=> 145,
                'brand'=> '',
                'category'=> "women's clothing",
                'thumbnail'=> 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
                'images'=> json_encode([]),
                'created_at'=> '2024-05-20T23:12:50.000000Z',
                'updated_at'=> '2024-05-20T23:12:50.000000Z'
            ]
        ];
        // Insert prducts into the database
        foreach ( $products as $product ) {
            Product::create( $product );
        }
    }
}
